db=db.getSiblingDB("customerTransactions");
db.product.drop();
db.customer.drop();
db.product.insert ({upc : '10001', brand: "Welsh Farms", product_name:'Whole Milk 1 Gal', product_Description:'Welsh Farms Whole Milk Size 1 Gallon', category:'Dairy', marked_price:3.5, quantity:30});
db.product.insert ({upc : '10002', brand: "Eggland", product_name:'Eggs L 12ct', product_Description:'Large Eggs - 12 count', category:'Dairy', marked_price:2.25, quantity:19});
db.product.insert ({upc : '10003', brand: "Kraft", product_name:'Kraft Mac n Cheese', product_Description:'Kraft Macaroni and Cheese Original Flavor Individual Box', category:'Food', marked_price:1.69, quantity:38});
db.product.insert ({upc : '10004', brand: "Rice-a-Roni", product_name:'Rice-A-Roni Cajun', category:'Food', marked_price:1.3, quantity:49});
db.product.insert ({upc : '10005', brand: "Pringles", product_name:'Pringles Sour Cream and Onion', product_Description:'Pringles Potato Chips - Sour Cream and Onion Flavor - 6 oz', category:'Snack', marked_price:4.5, quantity:28});
db.product.insert ({upc : '10006', brand: "Tostitos", product_name:'Tostitos Family Size', product_Description:'Tostitos Corn Chips - Family Size 1 lb', category:'Snack', marked_price:6, quantity:18});
db.product.insert ({upc : '10007', brand: "Store Brand", product_name:'Lettuce', product_Description:'Lettuce - 1 head', category:'Produce', marked_price:2.5, quantity:24});
db.product.insert ({upc : '10008', brand: "Store Brand", product_name:'Tomatoes', product_Description:'Tomatoes - 1 lb', category:'Produce', marked_price:1.99, quantity:12});
db.product.insert ({upc : '10009', brand: "Florida Natural", product_name:'Oranges', product_Description:'Oranges - Large Size - 1 lb', category:'Produce', marked_price:3.5, quantity:38});
db.product.insert ({upc : '10010', brand: "Store Brand", product_name:'Broccoli', product_Description:'Fresh Broccoli Crowns - 1 lb', category:'Produce', marked_price:3.5, quantity:17});
db.product.insert ({upc : '10011', brand: "Tropicana", product_name:'Tropicana Pure Premium OJ 1 Gal', product_Description:'Tropicana Pure Premium Orange Juice - Size 1 Gallon', category:'Beverages', marked_price:3.99, quantity:48});
db.product.insert ({upc : '10012', brand: "Coca-Cola", product_name:'Coca-Cola 2L', product_Description:'Coca-Cola Regular - Size 2 Liters', category:'Beverages', marked_price:1.99, quantity:94});
db.product.insert ({upc : '10013', brand: "Pepsi", product_name:'Pepsi 2L', product_Description:'Pepsi Regular - Size 2 Liters', category:'Beverages', marked_price:1.99, quantity:50});
db.product.insert ({upc : '10014', brand: "Pepsi", product_name:'Diet Pepsi 2L', product_Description:'Diet Pepsi - Size 2 Liters', category:'Beverages', marked_price:1.99, quantity:30});
db.product.insert ({upc : '10015', brand: "Colgate", product_name:'Colgate Winterfresh', product_Description:'Colgate Toothpaste Winterfresh Flavor 3.8 oz', category:'Pharmacy', marked_price:4, quantity:26});
db.product.insert ({upc : '10016', brand: "Crest", product_name:'Crest Whitening Mint', product_Description:'Crest Whitening Toothpaste - Mint Flavor 3.6 oz', category:'Pharmacy', marked_price:3.79, quantity:28});
db.product.insert ({upc : '10017', brand: "Claritin", product_name:'Claritin 24 Hour', product_Description:'Claritin 24 Hour Allergy Relief - 90 ct', category:'Pharmacy', marked_price:13.59, quantity:18});
db.product.insert ({upc : '10018', brand: "Store Brand", product_name:'Beef Top Sirloin', product_Description:'Fresh Beef - Cut Top Sirloin - 1 lb', category:'Meat', marked_price:8.99, quantity:27});
db.product.insert ({upc : '10019', brand: "Store Brand", product_name:'Pork Shoulder', product_Description:'Fresh Pork - Cut Shoulder - 1 lb', category:'Meat', marked_price:6.59, quantity:9});
db.product.insert ({upc : '10020', brand: "Store Brand", product_name:'Ground Chuck', product_Description:'Beef - Ground Chuck 94 percent Lean - 1 lb', category:'Meat', marked_price:6, quantity:22});
db.product.insert ({upc : '10021', brand: "Boars Head", product_name:'Honed Glazed Ham', product_Description:'Deli Meat - Honey Glazed Ham - 1 lb', category:'Deli', marked_price:7.5, quantity:51});
db.product.insert ({upc : '10022', brand: "Boars Head", product_name:'Oven Smoked Turkey', product_Description:'Deli Meat - Oven Smoked Turkey - 1 lb', category:'Deli', marked_price:7.5, quantity:15});
db.product.insert ({upc : '10023', brand: "Kraft", product_name:'Sliced Provolone', product_Description:'Deli Cheese - Sliced Provolone - 1 lb', category:'Deli', marked_price:5.5, quantity:29});
db.product.insert ({upc : '10024', brand: "Kraft", product_name:'Sliced Jarlsberg', product_Description:'Deli Cheese - Sliced Jarlsberg - 1 lb', category:'Deli', marked_price:5.5, quantity:21});
db.product.insert ({upc : '10025', brand: "Arnold", product_name:'Hot Dog Buns', product_Description:'Arnold Hot Dog Buns - 6 ct', category:'Bakery', marked_price:2, quantity:92});
db.product.insert ({upc : '10026', brand: "Arm and Hammer", product_name:'Baking Soda', product_Description:'Arm and Hammer Baking Soza - 1 lb', category:'Household', marked_price:9, quantity:39});
db.product.insert ({upc : '10027', brand: "Charmin", product_name:'Charmin Extra Soft Family Pack', product_Description:'Charmin Extra Soft Bathroom Tissue - 16 ct', category:'Household', marked_price:15, quantity:15});
db.product.insert ({upc : '10028', brand: "Kleenex", product_name:'Kleenex 250', product_Description:'Kleenex Tissue - 250 ct - floral box', category:'Household', marked_price:3, quantity:41});
db.product.insert ({upc : '10029', brand: "Budweiser", product_name:'Bud Light 24-pk', product_Description:'Bud Light Case of Beer - 24 count', category:'Alcohol', marked_price:29.99, quantity:10});
db.product.insert ({upc : '10030', brand: "Budweiser", product_name:'Budweiser 24-pk', product_Description:'Original Budweiser Case of Beer - 24 count', category:'Alcohol', marked_price:29.99, quantity:20});
db.product.insert ({upc : '10031', brand: "Coors", product_name:'Coors Light 12-pk', product_Description:'Original Coors The Banquet Beer 12 Pack', category:'Alcohol', marked_price:16.5, quantity:73});
db.product.insert ({upc : '10032', brand: "Miller", product_name:'MGD 12-pk', product_Description:'Miller Genuine Draft Beer 12 Pack', category:'Alcohol', marked_price:16.5, quantity:27});
db.customer.insert ({customer_ID : '1', first_name:'David', last_name:'Smith', age:30, gender:'M', zip_code:'22030' , transaction : []});
db.customer.insert ({customer_ID : '2', first_name:'Candice', last_name:'Bolton', age:27, gender:'F', zip_code:'22030' , transaction : []});
db.customer.insert ({customer_ID : '3', first_name:'David', last_name:'Goldenberg', age:65, gender:'M', zip_code:'22030' , transaction : []});
db.customer.insert ({customer_ID : '4', first_name:'Greg', last_name:'Jennings', age:25, gender:'M', zip_code:'22030' , transaction : []});
db.customer.insert ({customer_ID : '5', first_name:'Aaron', last_name:'Rodgers', age:32, gender:'M', zip_code:'20121' , transaction : []});
db.customer.insert ({customer_ID : '6', first_name:'Lindsey', last_name:'Lohan', age:24, gender:'F', zip_code:'20121' , transaction : []});
db.customer.insert ({customer_ID : '7', first_name:'Alec', last_name:'Baldwin', age:62, gender:'M', zip_code:'20121' , transaction : []});
db.customer.insert ({customer_ID : '8', first_name:'John', last_name:'Wayne', age:37, gender:'M', zip_code:'22030' , transaction : []});
db.customer.insert ({customer_ID : '9', first_name:'John', last_name:'Wayne', age:31, gender:'M', zip_code:'22015' , transaction : []});
db.customer.insert ({customer_ID : '10', first_name:'Jennifer', last_name:'Johnson', age:19, gender:'F', zip_code:'22030' , transaction : []});
db.customer.update ({customer_ID: '4'}, { $push: { transaction : { transaction_ID : '101', transaction_date:'10-FEB-13', payment_method:'1', total:28.17 , transaction_contains : [] }}});
db.customer.update ({customer_ID: '9'}, { $push: { transaction : { transaction_ID : '102', transaction_date:'12-FEB-13', payment_method:'2', total:36.48 , transaction_contains : [] }}});
db.customer.update ({customer_ID: '1'}, { $push: { transaction : { transaction_ID : '103', transaction_date:'15-FEB-13', payment_method:'2', total:96.15 , transaction_contains : [] }}});
db.customer.update ({customer_ID: '10'}, { $push: { transaction : { transaction_ID : '104', transaction_date:'20-FEB-13', payment_method:'3', total:84.74 , transaction_contains : [] }}});
db.customer.update ({customer_ID: '3'}, { $push: { transaction : { transaction_ID : '105', transaction_date:'15-FEB-13', payment_method:'2', total:12.5 , transaction_contains : [] }}});
db.customer.update ({customer_ID: '1'}, { $push: { transaction : { transaction_ID : '106', transaction_date:'15-FEB-13', payment_method:'2', total:39.38 , transaction_contains : [] }}});
db.customer.update ({ "transaction.transaction_ID" : '101'}, { $push: { "transaction.$.transaction_contains" : { upc:'10003', quantity:2}}});
db.customer.update ({ "transaction.transaction_ID" : '101'}, { $push: { "transaction.$.transaction_contains" : { upc:'10005', quantity:3}}});
db.customer.update ({ "transaction.transaction_ID" : '101'}, { $push: { "transaction.$.transaction_contains" : { upc:'10012', quantity:1}}});
db.customer.update ({ "transaction.transaction_ID" : '101'}, { $push: { "transaction.$.transaction_contains" : { upc:'10013', quantity:5}}});
db.customer.update ({ "transaction.transaction_ID" : '102'}, { $push: { "transaction.$.transaction_contains" : { upc:'10001', quantity:1}}});
db.customer.update ({ "transaction.transaction_ID" : '102'}, { $push: { "transaction.$.transaction_contains" : { upc:'10002', quantity:2}}});
db.customer.update ({ "transaction.transaction_ID" : '102'}, { $push: { "transaction.$.transaction_contains" : { upc:'10003', quantity:5}}});
db.customer.update ({ "transaction.transaction_ID" : '102'}, { $push: { "transaction.$.transaction_contains" : { upc:'10005', quantity:1}}});
db.customer.update ({ "transaction.transaction_ID" : '102'}, { $push: { "transaction.$.transaction_contains" : { upc:'10009', quantity:1}}});
db.customer.update ({ "transaction.transaction_ID" : '102'}, { $push: { "transaction.$.transaction_contains" : { upc:'10014', quantity:2}}});
db.customer.update ({ "transaction.transaction_ID" : '102'}, { $push: { "transaction.$.transaction_contains" : { upc:'10015', quantity:2}}});
db.customer.update ({ "transaction.transaction_ID" : '103'}, { $push: { "transaction.$.transaction_contains" : { upc:'10010', quantity:4}}});
db.customer.update ({ "transaction.transaction_ID" : '103'}, { $push: { "transaction.$.transaction_contains" : { upc:'10011', quantity:1}}});
db.customer.update ({ "transaction.transaction_ID" : '103'}, { $push: { "transaction.$.transaction_contains" : { upc:'10012', quantity:2}}});
db.customer.update ({ "transaction.transaction_ID" : '103'}, { $push: { "transaction.$.transaction_contains" : { upc:'10014', quantity:2}}});
db.customer.update ({ "transaction.transaction_ID" : '103'}, { $push: { "transaction.$.transaction_contains" : { upc:'10015', quantity:1}}});
db.customer.update ({ "transaction.transaction_ID" : '103'}, { $push: { "transaction.$.transaction_contains" : { upc:'10017', quantity:1}}});
db.customer.update ({ "transaction.transaction_ID" : '103'}, { $push: { "transaction.$.transaction_contains" : { upc:'10018', quantity:2}}});
db.customer.update ({ "transaction.transaction_ID" : '103'}, { $push: { "transaction.$.transaction_contains" : { upc:'10020', quantity:1}}});
db.customer.update ({ "transaction.transaction_ID" : '103'}, { $push: { "transaction.$.transaction_contains" : { upc:'10023', quantity:1}}});
db.customer.update ({ "transaction.transaction_ID" : '103'}, { $push: { "transaction.$.transaction_contains" : { upc:'10025', quantity:3}}});
db.customer.update ({ "transaction.transaction_ID" : '103'}, { $push: { "transaction.$.transaction_contains" : { upc:'10032', quantity:2}}});
db.customer.update ({ "transaction.transaction_ID" : '104'}, { $push: { "transaction.$.transaction_contains" : { upc:'10012', quantity:4}}});
db.customer.update ({ "transaction.transaction_ID" : '104'}, { $push: { "transaction.$.transaction_contains" : { upc:'10030', quantity:3}}});
db.customer.update ({ "transaction.transaction_ID" : '104'}, { $push: { "transaction.$.transaction_contains" : { upc:'10010', quantity:5}}});
db.customer.update ({ "transaction.transaction_ID" : '104'}, { $push: { "transaction.$.transaction_contains" : { upc:'10002', quantity:1}}});
db.customer.update ({ "transaction.transaction_ID" : '104'}, { $push: { "transaction.$.transaction_contains" : { upc:'10031', quantity:2}}});
db.customer.update ({ "transaction.transaction_ID" : '105'}, { $push: { "transaction.$.transaction_contains" : { upc:'10005', quantity:2}}});
db.customer.update ({ "transaction.transaction_ID" : '105'}, { $push: { "transaction.$.transaction_contains" : { upc:'10004', quantity:3}}});
db.customer.update ({ "transaction.transaction_ID" : '106'}, { $push: { "transaction.$.transaction_contains" : { upc:'10021', quantity:1}}});
db.customer.update ({ "transaction.transaction_ID" : '106'}, { $push: { "transaction.$.transaction_contains" : { upc:'10027', quantity:2}}});

